### PR TITLE
Support fileinto :create (with mailbox capability)

### PR DESCRIPTION
**Pull request by Mortal**
Per https://tools.ietf.org/html/rfc5490#section-3.2

### CODE REVIEW

**Comment by tonioo** [comment]
@Mortal Sorry for the lack of response. Thank you for this contribution but could you please add a unit test please?

**Comment by Mortal** [comment]
Thanks - I'll see if I can look into it tomorrow. Feel free to ping me if I forget.

**Comment by Mortal** [comment]
@tonioo When adding unit tests I discovered a bug in how Command handles commands with two optional arguments that require different extensions. Probably this has not been encountered in sievelib before this PR. The bugfix included in this PR is covered by the new fileinto unit tests (without the bugfix, the test fails with "extension 'copy' not loaded", even though `:copy` is not specified).

**Comment by tonioo** [comment]
@Mortal Thank you.

**Pull request merged**
