### PR TITLE
Check if parsed command is a test one.

### PR DESCRIPTION
**Pull request by tonioo**
see #100

### CODE REVIEW

**Comment by derula** [comment]
This now is correctly recognized as an error:
```if anyof(address :contains "From" "" header :contains "Subject" "") {}```
But this one still doesn't give me an error even though it's wrong:
```if anyof(allof(address :contains "From" "") allof(header :contains "Subject" "")) {}```

**Comment by derula** [comment]
LGTM and doesn't seem to break anything I have an example for.

**Comment by derula** [comment]
Seems to work and not break anything (sorry for the deleted posts, I got confused which branch did what)

**Comment by tonioo** [comment]
@derula Thank you

**Pull request merged**
